<script>
	import { onMount } from 'svelte';
	import { get, writable } from 'svelte/store';
	import { fade, slide } from 'svelte/transition';
	import { superForm } from 'sveltekit-superforms';
	import { debounce } from 'throttle-debounce';
	import { beforeNavigate, goto } from '$app/navigation';
	import { page } from '$app/stores';

	import Icon from '$lib/components/Icon.svelte';
	import { Icons } from '$lib/components/icons/icons.js';

	import { useModals } from '$lib/stores/modals.js';
	import TaintedModal from '$lib/components/TaintedModal.svelte';
	import DeleteModal from '$lib/components/flashcards/DeleteModal.svelte';
	import RenameModal from '$lib/components/flashcards/RenameModal.svelte';

	import { useNavBar } from '$lib/stores/navbar.js';
	import NavBar from '$lib/components/NavBar.svelte';

	import AccountDropdown from '$lib/components/AccountDropdown.svelte';
	import Spinner from '$lib/components/Spinner.svelte';
	import Toolbar from '$lib/components/editor/Toolbar.svelte';

	import 'quill/dist/quill.core.css';
	import './editor.css';

	export let data;
	$: ({ supabase, deck, id } = data);

	const {
		form: create,
		errors: createErrors,
		constraints: createConstraints,
		enhance: createEnhance,
		delayed: createDelayed
	} = superForm(data.createForm, {
		invalidateAll: false,
		onUpdated({ form }) {
			if (form.valid) {
				// Add new flashcard to deck.flashcards
				flashcards.update((f) => {
					f.push({
						id: form.message,
						title: form.data.title
					});
					return f;
				});
			}
		}
	});

	const {
		enhance: saveEnhance,
		submit: saveSubmit,
		submitting: isSaving
	} = superForm(
		{
			id: data.flashcard.id,
			front: data.flashcard.front,
			back: data.flashcard.back
		},
		{
			invalidateAll: false,
			applyAction: false,
			multipleSubmits: 'abort',
			dataType: 'json',
			onSubmit({ cancel, jsonData }) {
				if (!$flashcard) {
					cancel();
				}

				// Save cursor position
				/* Generated by Perplexity on 11/14/24 */
				cursorIndex = quill.getSelection()?.index ?? 0;
				/* End generated code */

				if (isFront) {
					$flashcard.front = quill.getContents().ops;
				} else {
					$flashcard.back = quill.getContents().ops
				}

				jsonData({
					id: $flashcard.id,
					front: $flashcard.front,
					back: $flashcard.back
				});
			},
			onUpdated({ form }) {
				if (form.valid) {
					saved = true;
					// Restore cursor position
					/* Generated by Perplexity on 11/14/24 */
					quill.setSelection(cursorIndex, 0);
					/* End generated code */
				}
			}
		}
	);

	const save = debounce(2500, saveSubmit);

	const modals = useModals();
	const navBar = useNavBar();

	const flashcard = writable(data.flashcard);
	const flashcards = writable([]);
	let quill, editor, toolbar;
	let saved = true;
	let isCreating = false;
	let cursorIndex = 0;
	let isFront = true

	beforeNavigate((navigation) => {
		if (!saved) {
			navigation.cancel();
			modals.trigger({
				modal: TaintedModal,
				response: async (confirmed) => {
					if (confirmed) {
						saved = true;
						goto(navigation.to.url.href);
					}
				}
			});
		}
	});

	onMount(async () => {
		navBar.setTitle(deck.title);

		const { default: Quill } = await import('quill');
		quill = new Quill(editor, {
			modules: {
				toolbar: false
			},
			formats: [
				// 'background',
				'bold',
				'color',
				// 'font',
				'code',
				'italic',
				'link',
				'size',
				'strike',
				'script',
				'underline',
				'blockquote',
				'header',
				'indent',
				'list',
				// 'align',
				'direction',
				'code-block',
				'formula'
				// 'image' is excluded
			]
		});

		quill.on('text-change', (delta, oldDelta, source) => {
			if (source === 'user') {
				saved = false;
				save();
			}
		});

		quill.focus();

		quill.setContents($flashcard.front)
	});

	function flip() {
		if (isFront) {
			$flashcard.front = quill.getContents().ops
		} else {
			$flashcard.back = quill.getContents().ops
		}

		quill.setContents(isFront ? $flashcard.back : $flashcard.front)
		isFront = !isFront
	}

	$: $flashcards = deck.flashcards;
	$: $flashcard = data.flashcard;
</script>

<svelte:head>
	<title>Nitin | {deck.title}</title>
</svelte:head>

<NavBar>
	<svelte:fragment slot="right">
		<AccountDropdown />
	</svelte:fragment>
	<svelte:fragment slot="bottom">
		{#if quill}
			<Toolbar {quill} />
		{/if}
	</svelte:fragment>
	<svelte:fragment slot="menu">
		<div
			in:slide={{ axis: 'x' }}
			out:slide={{ axis: 'x' }}
			class="absolute left-0 top-[60px] h-[calc(100vh-60px)] w-full md:top-[152px] md:h-[calc(100vh-152px)] md:w-1/3 xl:max-w-[472px]"
		>
			<div
				class="flex w-full min-w-80 flex-col justify-between space-y-4 bg-stone-50/90 backdrop-blur dark:bg-stone-950/90"
			>
				{#if $flashcards.length > 0}
					<div
						class="mx-auto h-[calc(100vh-188px)] w-full overflow-y-auto pb-4 pt-4 md:h-[calc(100vh-281px)]"
						style="scrollbar-width: thin;"
					>
						{#each $flashcards as flashcard, i}
							<div
								class="mx-auto my-2 flex h-20 w-11/12 flex-row items-center rounded-3xl {flashcard.id ==
								id
									? 'bg-stone-200 dark:bg-stone-700'
									: 'bg-stone-100 dark:bg-stone-800'} border border-stone-400 px-4 hover:cursor-pointer hover:border-stone-700 hover:bg-stone-200 dark:border-stone-700 hover:dark:border-stone-500 hover:dark:bg-stone-700"
							>
								<div class="flex h-full items-center justify-center px-4 hover:cursor-grab">
									<Icon icon={Icons.DragIndicator} width="32" height="32" />
								</div>
								<a
									class="flex h-full w-full flex-row items-center overflow-hidden text-ellipsis whitespace-nowrap text-xl"
									href="/flashcards/{deck.id}/edit/{flashcard.id}"
									data-sveltekit-preload-data="false">{i + 1}. {flashcard.title}</a
								>
								<div class="flex w-full items-center justify-end">
									<button
										class="z-10 flex h-12 w-12 items-center justify-center rounded-lg hover:cursor-pointer hover:bg-stone-300 dark:hover:bg-stone-600"
										on:click={() => {
											modals.trigger({
												modal: RenameModal,
												props: {
													data: {
														renameForm: data.renameForm,
														flashcards,
														flashcard
													}
												}
											});
										}}
									>
										<Icon icon={Icons.Edit} width="32" height="32" />
									</button>
									<button
										class="icon-button-danger z-10 flex h-12 w-12 items-center justify-center rounded-lg hover:cursor-pointer hover:bg-stone-300 dark:hover:bg-stone-600"
										on:click={() =>
											modals.trigger({
												modal: DeleteModal,
												props: {
													data: {
														deleteForm: data.deleteForm,
														deck_id: deck.id,
														flashcards,
														flashcard
													}
												}
											})}
									>
										<Icon icon={Icons.Delete} width="32" height="32" />
									</button>
								</div>
							</div>
						{/each}
						{#if isCreating}
							<div
								class="mx-auto my-2 flex h-20 w-11/12 flex-row items-center rounded-3xl border border-stone-400 bg-stone-100 px-4 dark:border-stone-700 dark:bg-stone-800"
								in:fade={{ duration: 150 }}
								out:fade={{ duration: 150 }}
							>
								<div class="flex h-full items-center justify-center px-4">
									<Icon icon={Icons.DragIndicator} width="32" height="32" fill={'#78716c'} />
								</div>
								<span class="pr-2 text-xl">{$flashcards.length + 1}. </span>
								<form
									class="flex w-full flex-row items-center justify-between"
									method="POST"
									action="?/create"
									use:createEnhance
									novalidate
								>
									<input class="hidden" name="deck_id" type="text" bind:value={deck.id} />
									<div class="relative">
										<input
											class="form-input mr-2"
											name="title"
											type="text"
											placeholder="My Flashcard"
											aria-invalid={$createErrors.title ? 'true' : undefined}
											bind:value={$create.title}
											{...$createConstraints.title}
										/>
										{#if $createErrors.title}
											<div
												in:fade
												class="absolute right-2 top-3 mt-1 flex items-center justify-center"
											>
												<Icon icon={Icons.Error} width="20" height="20" fill={'#ef4444'} />
											</div>
										{/if}
									</div>
									<button
										class="flex h-12 w-12 items-center justify-center rounded-lg px-2 hover:cursor-pointer hover:bg-stone-300 dark:hover:bg-stone-600"
										type="submit"
									>
										{#if $createDelayed}
											<div in:fade>
												<Spinner fill={'#fafaf9'} />
											</div>
										{:else}
											<Icon icon={Icons.ForwardArrow} width="32" height="32" />
										{/if}
									</button>
								</form>
							</div>
						{/if}
						<div class="h-72 w-full sm:h-0"></div>
					</div>
				{/if}
				<div class="mx-6 flex h-28 flex-row items-center justify-between pb-10 pt-4">
					<a href="/flashcards" class="flex flex-row items-center" on:click={() => navBar.hide()}>
						<div class="btn-outline mr-6 h-10 w-10 rounded-md" href="/flashcards">
							<div class="absolute left-[3px] top-[3px] h-8 w-8">
								<Icon icon={Icons.BackArrow} width="32" height="32" />
							</div>
						</div>
						<span class="text-nowrap text-lg font-semibold">All Flashcards</span>
					</a>
					<button
						class="btn-outline h-16 w-16 rounded-full shadow-md"
						on:click={() => (isCreating = !isCreating)}
					>
						<div
							class="{isCreating
								? 'rotate-[315deg]'
								: ''} transition-transform duration-500 ease-in-out"
						>
							<Icon icon={Icons.Plus} width="32" height="32" />
						</div>
					</button>
				</div>
			</div>
		</div>
	</svelte:fragment>
</NavBar>

<div class="container relative z-20 mx-auto w-full px-4">
	<div
		class="bg-stone-20 sticky float-right mt-4 flex w-[80px] flex-row items-center justify-center rounded-md border border-stone-400 dark:border-stone-700 dark:bg-stone-950"
	>
		<button
			class="flex h-10 w-10 items-center justify-center rounded-l-md {isFront ? "bg-stone-200 dark:bg-stone-800" : "bg-stone-50 dark:bg-stone-950"}  hover:cursor-pointer hover:bg-stone-300 dark:hover:bg-stone-700"
			on:click={() => { 
				if (!isFront) {
					flip()
				}
			}}
		>
			<div>
				<Icon icon={Icons.FlipToFront} width="32" height="32" />
			</div>
		</button>
		<button
			class="flex h-10 w-10 items-center justify-center rounded-r-md {!isFront ? "bg-stone-200 dark:bg-stone-800" : "bg-stone-50 dark:bg-stone-950"} hover:cursor-pointer hover:bg-stone-300 dark:hover:bg-stone-700"
			on:click={() => { 
				if (isFront) {
					flip()
				}
			}}
		>
			<div>
				<Icon icon={Icons.FlipToBack} width="32" height="32" />
			</div>
		</button>
	</div>
</div>

<div
	class="fixed left-0 top-[196px] h-[calc(100%-196px)] min-h-[calc(100vh-196px)] w-full overflow-y-auto bg-stone-100 dark:bg-stone-900 min-[560px]:top-[152px] min-[560px]:h-[calc(100%-152px)] min-[560px]:min-h-[calc(100vh-152px)]"
>
	<div class="container mx-auto px-4">
		<span class="my-6 block text-xl text-stone-500">{$flashcard.title} {!saved ? '*' : ''}</span>
		<div bind:this={editor}>
			<Spinner />
		</div>
		<div class="pt-20"></div>
	</div>
</div>

<form class="hidden" method="POST" action="?/save" use:saveEnhance></form>
