/* Generated by GPT-4o on 11/14/24 */
export const schema = {
	$schema: 'http://json-schema.org/draft-07/schema#',
	type: 'object',
	properties: {
		id: {
			type: 'string',
			format: 'uuid'
		},
		front: {
			type: 'array',
			minItems: 0, // Allow empty array
			items: {
				type: 'object',
				properties: {
					insert: { type: ['string', 'object'] },
					attributes: {
						type: 'object',
						properties: {
							size: { type: 'string' },
							bold: { type: 'boolean' },
							italic: { type: 'boolean' },
							underline: { type: 'boolean' },
							strike: { type: 'boolean' },
							color: { type: 'string' },
							link: { type: 'string' },
							header: { type: 'integer' },
							list: { type: 'string' }
						},
						additionalProperties: false
					}
				},
				required: ['insert'],
				additionalProperties: false
			}
		},
		back: {
			type: 'array',
			minItems: 0, // Allow empty array
			items: {
				type: 'object',
				properties: {
					insert: { type: ['string', 'object'] },
					attributes: {
						type: 'object',
						properties: {
							bold: { type: 'boolean' },
							italic: { type: 'boolean' },
							underline: { type: 'boolean' },
							strike: { type: 'boolean' },
							color: { type: 'string' },
							link: { type: 'string' },
							header: { type: 'integer' },
							list: { type: 'string' }
						},
						additionalProperties: false
					}
				},
				required: ['insert'],
				additionalProperties: false
			}
		}
	},
	required: ['id', 'front', 'back'],
	additionalProperties: false
};
/* End generated code */
