<script>
    import { goto } from '$app/navigation';
    import { onMount } from 'svelte';
    import { useModals } from '$lib/stores/modals.js';
    import DeleteQuestionModal from '$lib/components/quizzes/DeleteQuestionModal.svelte';  

    $: ({ supabase } = data);
    export let data;
    const modals = useModals();

    // =============================================
    // State Initialization
    // =============================================
    
    /* Generated by GPT-4o */ 

    // Initialize questions from existing data or create empty question template
    let questions = data.questions?.length > 0 ? data.questions.map(q => ({
        id: q.id,
        question: q.question,
        order: q.order,
        answers: q.answers.map(a => ({
            id: a.id,
            text: a.answer,
            isCorrect: a.is_correct,
            order: a.order
        }))
    })) : [{
        question: '',
        order: 0,
        answers: [
            { text: '', isCorrect: false, order: 0 },
            { text: '', isCorrect: false, order: 1 },
            { text: '', isCorrect: false, order: 2 },
            { text: '', isCorrect: false, order: 3 }
        ]
    }];

    /* End Generated Code */

    // =============================================
    // Question Management Functions
    // =============================================
    
    // Adds a new empty question to the quiz with default answer options
    function addQuestion() {
        const newOrder = questions.length;
        questions = [...questions, {
            question: '',
            order: newOrder,
            answers: [
                { text: '', isCorrect: false, order: 0 },
                { text: '', isCorrect: false, order: 1 },
                { text: '', isCorrect: false, order: 2 },
                { text: '', isCorrect: false, order: 3 }
            ]
        }];
    }

    // Handles the deletion of a question, including database cleanup if necessary
    async function handleQuestionDelete(questionToDelete) {
        try {
            // Delete answers first
            const { error: answersError } = await supabase
                .from('answers')
                .delete()
                .eq('question_id', questionToDelete.id);
                
            if (answersError) throw answersError;

            // Then delete the question
            const { error: questionError } = await supabase
                .from('questions')
                .delete()
                .eq('id', questionToDelete.id);
                
            if (questionError) throw questionError;
            
            return true;
        } catch (error) {
            console.error('Error deleting question:', error);
            return false;
        }
    }

    /* Generated by GPT-4o */ 

    // Initiates the question deletion process, showing confirmation modal if needed
    function deleteQuestion(index) {
        const questionToDelete = questions[index];
        if (!questionToDelete.id) {
            // If question hasn't been saved yet, just remove it from the array
            questions = questions
                .filter((_, i) => i !== index)
                .map((q, i) => ({ ...q, order: i }));
            return;
        }

        modals.trigger({
            modal: DeleteQuestionModal,
            props: {
                questionIndex: index,
                questionText: questionToDelete.question,
                onDelete: async () => {
                    const success = await handleQuestionDelete(questionToDelete);
                    if (success) {
                        questions = questions
                            .filter((_, i) => i !== index)
                            .map((q, i) => ({ ...q, order: i }));
                    }
                }
            }
        });
    }

    /* End Generated Code */

    // =============================================
    // Answer Management Functions
    // =============================================
    
    // Sets the correct answer for a question, ensuring only one answer is marked correct
    function setCorrectAnswer(questionIndex, answerIndex) {
        questions = questions.map((question, currentQuestionIndex) => {
            if (currentQuestionIndex === questionIndex) {
                return {
                    ...question,
                    answers: question.answers.map((answer, currentAnswerIndex) => ({
                        ...answer,
                        isCorrect: currentAnswerIndex === answerIndex
                    }))
                };
            }
            return question;
        });
    }

    // =============================================
    // Quiz Save/Update Functions
    // =============================================
    
    // Saves the entire quiz, handling both new questions and updates to existing ones
    async function saveQuiz() {
        const quizId = data.quiz?.id;
        
        if (!quizId) return;

        const { data: existingQuestions } = await supabase
            .from('questions')
            .select('id')
            .eq('quiz_id', quizId);

    /* Generated by GPT-4o */ 

        if (existingQuestions?.length) {
            const questionIds = existingQuestions.map(q => q.id);
            await supabase
                .from('answers')
                .delete()
                .in('question_id', questionIds);

            await supabase
                .from('questions')
                .delete()
                .eq('quiz_id', quizId);
        }

    /* End Generated Code */

        // Create new questions and answers
        for (const question of questions) {
            const { data: savedQuestion, error: questionError } = await supabase
                .from('questions')
                .insert([{
                    quiz_id: quizId,
                    question: question.question,
                    order: question.order
                }])
                .select()
                .single();

            if (questionError) return;

            const answersToInsert = question.answers.map(answer => ({
                question_id: savedQuestion.id,
                answer: answer.text,
                is_correct: answer.isCorrect,
                order: answer.order
            }));

            const { error: answersError } = await supabase
                .from('answers')
                .insert(answersToInsert);

            if (answersError) return;
        }

        goto('/quizzes');
    }
</script>

<!-- =============================================
     Component Template
     ============================================= -->

<!-- did by self but got some help from GPT-4o -->

<div class="max-w-2xl mx-auto p-4">
    <h1 class="text-2xl font-bold mb-4">{data.quiz ? 'Edit Quiz' : 'Create Quiz'}</h1>
    
    {#each questions as question, questionIndex}
        <div class="mb-8 p-4 border rounded border-stone-400 dark:border-stone-700">
            <div class="flex justify-between items-center mb-2">
                <label for={`question-${questionIndex}`} class="form-label">Question {questionIndex + 1}:</label>
                {#if questions.length > 1}
                    <button
                        type="button"
                        class="text-red-500 hover:text-red-700 font-medium"
                        on:click={() => deleteQuestion(questionIndex)}
                    >
                        Delete Question
                    </button>
                {/if}
            </div>
            
            <input
                id={`question-${questionIndex}`}
                type="text"
                bind:value={question.question}
                class="form-input"
                placeholder="Enter question"
                autocomplete="off"
            />

            <div class="space-y-1">
                {#each question.answers as answer, answerIndex}
                    <div class="flex items-center gap-4">
                        <input
                            type="radio"
                            name="correct-{questionIndex}"
                            checked={answer.isCorrect}
                            on:change={() => setCorrectAnswer(questionIndex, answerIndex)}
                            class="checkbox"
                        />
                        <input
                            type="text"
                            bind:value={answer.text}
                            class="form-input"
                            placeholder={`Answer ${answerIndex + 1}`}
                        />
                    </div>
                {/each}
            </div>
        </div>
    {/each}

    <div class="flex gap-4">
        <button
            on:click={addQuestion}
            class="btn-primary"
        >
            Add Question
        </button>
        <button
            on:click={saveQuiz}
            class="btn-primary"
        >
            Save Quiz
        </button>
        <button
            on:click={() => goto('/quizzes')}
            class="btn-secondary"
        >
            Cancel
        </button>
    </div>
</div>