<script>
    import { goto } from '$app/navigation';
    import { onMount } from 'svelte';
    import { page } from '$app/stores';

    // =============================================
    // State Initialization
    // =============================================
    
    export let data;
    $: ({ supabase } = data);

    // Quiz state variables
    let quiz = null;
    let currentQuestions = [];
    let userAnswers = {};   

    // Initialize quiz on component mount
    onMount(async () => {
        const quizId = $page.params.id;
        await loadQuiz(quizId);
    });

    // =============================================
    // Data Loading Functions
    // =============================================
    
    // Loads quiz details and its associated questions/answers from the database
    async function loadQuiz(quizId) {
        // Load quiz details
        const { data: quizData } = await supabase
            .from('quizzes')
            .select('*')
            .eq('id', quizId)
            .single();

        if (!quizData) return;

        quiz = quizData;
        
        // Load questions and answers
        const { data: questionsData } = await supabase
            .from('questions')
            .select(`
                id,
                question,
                order,
                answers (
                    id,
                    answer,
                    is_correct,
                    order
                )
            `)
            .eq('quiz_id', quizId)
            .order('order');

    /* Generated by GPT-4o */ 

        currentQuestions = (questionsData || []).map(q => ({
            ...q,
            answers: q.answers.sort((a, b) => a.order - b.order)
        }));

    /* End Generated Code */

    }

    // =============================================
    // Quiz Handling Functions
    // =============================================
    
    /* mostly done by self but got help from GPT-4o */ 

    // Calculates score and redirects to results page
    function submitQuiz() {
        const correctAnswers = currentQuestions.reduce((total, question) => {
            const userAnswer = userAnswers[question.id];
            const correctAnswer = question.answers.find(a => a.is_correct);
            return userAnswer === correctAnswer?.id ? total + 1 : total;
        }, 0);

        const score = (correctAnswers / currentQuestions.length) * 100;
        goto(`/quizzes/${$page.params.id}/results?score=${score}&title=${encodeURIComponent(quiz.title)}`);
    }
</script>

<!-- =============================================
     Component Template
     ============================================= -->

<div class="max-w-2xl mx-auto p-4">
    <div class="flex justify-between items-center mb-6">
        <h1 class="text-2xl font-bold">Study Quiz</h1>
        <button 
            class="btn-secondary"
            on:click={() => goto('/quizzes')}
        >
            Back to Quizzes
        </button>
    </div>

    {#if quiz && currentQuestions.length > 0}
        <div class="space-y-6">
            <h2 class="text-xl mb-4">{quiz.title || 'Untitled Quiz'}</h2>
            {#each currentQuestions as question}
                <div class="p-4 border rounded border-stone-400 dark:border-stone-700">
                    <p class="form-label mb-4">{question.question}</p>
                    
                    <div class="space-y-2">
                        {#each question.answers as answer}
                            <label class="flex items-center gap-2">
                                <input
                                    type="radio"
                                    name="question-{question.id}"
                                    value={answer.id}
                                    bind:group={userAnswers[question.id]}
                                    class="checkbox"
                                />
                                <span>{answer.answer}</span>
                            </label>
                        {/each}
                    </div>
                </div>
            {/each}

            <button
                on:click={submitQuiz}
                class="btn-primary"
            >
                Submit Quiz
            </button>
        </div>
    {:else}
        <div class="text-center p-4">
            <p>Loading quiz...</p>
        </div>
    {/if}
</div>