export const schema = {
	type: 'object',
	properties: {
		title: {
			type: 'string',
			maxLength: 32,
			/* Generated by Perplexity on 10/29/24 */
			pattern: '^\\S+.*\\S$|^\\S$'
			/* End generated code */
		}
	},
	required: ['title'],
	additionalProperties: false,
	$schema: 'http://json-schema.org/draft-07/schema#'
};
