<script>
	import { onMount } from 'svelte';
	import { writable } from 'svelte/store';

	import { Icons } from '../icons/icons';
	import Icon from '../Icon.svelte';

	import FileDropdown from '../flashcards/FileDropdown.svelte';
	import EditDropdown from './EditDropdown.svelte';
	import FormatDropdown from './FormatDropdown.svelte';
	import TextSizeDropdown from './TextSizeDropdown.svelte';

	import { formatStore } from './format';

	export let quill;

	const activeColor = '#3b82f6';

	let textSize = writable(undefined);

	onMount(() => {
		quill.on('selection-change', (range, oldRange, source) => {
			if (range) {
				update(range);
			}
		});

		// Number list is removed by deleting text
		quill.on('text-change', (delta, oldDelta, source) => {
			const selection = quill.getSelection();
			if (selection) {
				update(selection);
			}
		});
	});

	function update(range) {
		const format = quill.getFormat(range);
		$textSize = format.size;
		formatStore.set({
			isBold: format.bold,
  		isItalic: format.italic,
			isUnderline: format.underline,
			isStrikethrough: format.strike,
			isNumberedList: format.list === 'ordered',
			isBulletedList: format.list === 'bullet'
		});
	}

	function bold() {
		/* Generated by Perplexity on 11/10/24 */
		const selection = quill.getSelection();
		if (selection) {
			quill.format('bold', !quill.getFormat(selection).bold);
			formatStore.update(state => ({ ...state, isBold: quill.getFormat(selection).bold}))
		}
		/* End generated code */
	}

	function italic() {
		const selection = quill.getSelection();
		if (selection) {
			quill.format('italic', !quill.getFormat(selection).italic);
			formatStore.update(state => ({ ...state, isItalic: quill.getFormat(selection).italic}))
		}
	}

	function underline() {
		const selection = quill.getSelection();
		if (selection) {
			quill.format('underline', !quill.getFormat(selection).underline);
			formatStore.update(state => ({ ...state, isUnderline: quill.getFormat(selection).underline}))
		}
	}

	function strikethrough() {
		const selection = quill.getSelection();
		if (selection) {
			quill.format('strike', !quill.getFormat(selection).strike);
			formatStore.update(state => ({ ...state, isStrikethrough: quill.getFormat(selection).strike}))
		}
	}

	function numberedList() {
		const selection = quill.getSelection();
		if (selection) {
			quill.format('list', $formatStore.isNumberedList ? false : 'ordered');
			formatStore.update(state => ({ ...state, isNumberedList: quill.getFormat(selection).list === 'ordered'}))
		}
	}

	function bulletedList() {
		const selection = quill.getSelection();
		if (selection) {
			quill.format('list', $formatStore.isBulletedList ? false : 'bullet');
			formatStore.update(state => ({ ...state, isItalic: quill.getFormat(selection).list === 'bullet'}))
		}
	}
</script>

<div class="flex flex-row items-center justify-start space-x-1 pt-1.5">
	<FileDropdown />
	<EditDropdown />
	<FormatDropdown
		on:bold={() => bold()}
		on:italic={() => italic()}
		on:underline={() => underline()}
		on:strikethrough={() => strikethrough()}
		on:numberedlist={() => numberedList()}
		on:bulletedlist={() => bulletedList()}
	/>
</div>
<div class="flex min-w-80 flex-row flex-wrap items-center justify-start space-x-1 space-y-1 pt-1.5">
	<TextSizeDropdown
		selection={textSize}
		on:select={() => {
			const selection = quill?.getSelection();
			if (selection) {
				quill.format('size', $textSize);
			}
		}}
	/>
	<button
		class="rounded-lg p-1 {$formatStore.isBold
			? 'bg-stone-200 dark:bg-stone-800'
			: 'bg-stone-50 dark:bg-stone-950'} hover:cursor-pointer hover:bg-stone-200 hover:dark:bg-stone-800"
		on:click={() => bold()}
	>
		<Icon icon={Icons.Bold} width="32" height="32" fill={$formatStore.isBold ? activeColor : null} />
	</button>
	<button
		class="rounded-lg p-1 {$formatStore.isItalic
			? 'bg-stone-200 dark:bg-stone-800'
			: 'bg-stone-50 dark:bg-stone-950'} hover:cursor-pointer hover:bg-stone-200 hover:dark:bg-stone-800"
		on:click={() => italic()}
	>
		<Icon icon={Icons.Italic} width="32" height="32" fill={$formatStore.isItalic ? activeColor : null} />
	</button>
	<button
		class="self-end rounded-lg p-1 {$formatStore.isUnderline
			? 'bg-stone-200 dark:bg-stone-800'
			: 'bg-stone-50 dark:bg-stone-950'} hover:cursor-pointer hover:bg-stone-200 hover:dark:bg-stone-800"
		on:click={() => underline()}
	>
		<Icon icon={Icons.Underline} width="32" height="32" fill={$formatStore.isUnderline ? activeColor : null} />
	</button>
	<button
		class="rounded-lg p-1 {$formatStore.isStrikethrough
			? 'bg-stone-200 dark:bg-stone-800'
			: 'bg-stone-50 dark:bg-stone-950'} hover:cursor-pointer hover:bg-stone-200 hover:dark:bg-stone-800"
		on:click={() => strikethrough()}
	>
		<Icon
			icon={Icons.Strikethrough}
			width="32"
			height="32"
			fill={$formatStore.isStrikethrough ? activeColor : null}
		/>
	</button>
	<button
		class="rounded-lg p-1 {$formatStore.isNumberedList
			? 'bg-stone-200 dark:bg-stone-800'
			: 'bg-stone-50 dark:bg-stone-950'}
			hover:cursor-pointer hover:bg-stone-200 hover:dark:bg-stone-800"
		on:click={() => numberedList()}
	>
		<Icon
			icon={Icons.NumberedList}
			width="32"
			height="32"
			fill={$formatStore.isNumberedList ? activeColor : null}
		/>
	</button>
	<button
		class="rounded-lg p-1 {$formatStore.isBulletedList
			? 'bg-stone-200 dark:bg-stone-800'
			: 'bg-stone-50 dark:bg-stone-950'} hover:cursor-pointer hover:bg-stone-200 hover:dark:bg-stone-800"
		on:click={() => bulletedList()}
	>
		<Icon
			icon={Icons.BulletedList}
			width="32"
			height="32"
			fill={$formatStore.isBulletedList ? activeColor : null}
		/>
	</button>
	<div class="rounded-lg p-1 hover:cursor-pointer hover:bg-stone-200 hover:dark:bg-stone-800">
		<Icon icon={Icons.AddLink} width="32" height="32" />
	</div>
	<div class="h-8 w-[1px] bg-stone-400 dark:bg-stone-800"></div>
	<div class="rounded-lg p-1 hover:cursor-pointer hover:bg-stone-200 hover:dark:bg-stone-800">
		<Icon icon={Icons.AddPhoto} width="32" height="32" />
	</div>
	<div class="rounded-lg p-1 hover:cursor-pointer hover:bg-stone-200 hover:dark:bg-stone-800">
		<Icon icon={Icons.Draw} width="32" height="32" />
	</div>
</div>
