<script>
	import { onMount } from 'svelte';
	import { writable } from 'svelte/store';

	import { Icons } from '../icons/icons';
	import Icon from '../Icon.svelte';

	import FileDropdown from '../flashcards/FileDropdown.svelte';
	import EditDropdown from './EditDropdown.svelte';
	import FormatDropdown from './FormatDropdown.svelte';
	import TextSizeDropdown from './TextSizeDropdown.svelte';

	import { debounce } from 'throttle-debounce';

	import { formatStore } from './format';

	export let quill;

	const activeColor = '#3b82f6';
	const flashcardId = new URLSearchParams(window.location.search).get('id');

	let textSize = writable(undefined);
	let drawing = false;
	let isDrawing = false;
	let canvas, ctx;
	let strokes = [];
	let saved = true;

	onMount(() => {
		quill.on('selection-change', (range, oldRange, source) => {
			if (range) {
				update(range);
			}
		});

		// Number list is removed by deleting text
		quill.on('text-change', (delta, oldDelta, source) => {
			const selection = quill.getSelection();
			if (selection) {
				update(selection);
			}
		});

		if (canvas) {
			ctx = canvas.getContext('2d');
			canvas.width = quill.root.clientWidth;
			canvas.height = quill.root.clientHeight;
			
			
			canvas.addEventListener('mousedown', startDrawing);
			canvas.addEventListener('mousemove', draw);
			canvas.addEventListener('mouseup', stopDrawing);
			canvas.addEventListener('mouseout', stopDrawing);
		}
	});

	function updateCanvasHeight () {
		const quillHeight = quill.root.clientHeight;
		canvas.height = quillHeight;
	}
	quill.on('text-change', updateCanvasHeight);

	function update(range) {
		const format = quill.getFormat(range);
		$textSize = format.size;
		formatStore.set({
			isBold: format.bold,
  		isItalic: format.italic,
			isUnderline: format.underline,
			isStrikethrough: format.strike,
			isNumberedList: format.list === 'ordered',
			isBulletedList: format.list === 'bullet'
		});
	}

	function toggleDrawing() {
		drawing = !drawing;
		if (drawing) {
			canvas.style.pointerEvents = 'auto';  // Allow pointer events when drawing
			saved = false;
		} else {
			canvas.style.pointerEvents = 'none'; // Disable pointer events when not drawing
		}
	}

	function startDrawing(event) {
		if (drawing){
			isDrawing = true;
			ctx.beginPath();
			ctx.moveTo(event.offsetX, event.offsetY);

			ctx.strokeStyle = 'white';
			ctx.lineWidth = 2;         
			ctx.lineCap = 'round';     

			strokes.push({
				startX: event.offsetX,
				startY: event.offsetY,
				color: 'white',
				width: '2',
				lineCap: 'round',
				path: [{ x: event.offsetX, y: event.offsetY }]
			});
			console.log(strokes);
		}
	}

	function draw(event) {
		if (drawing && isDrawing){
			ctx.lineTo(event.offsetX, event.offsetY);
			ctx.stroke();

			const currentStroke = strokes[strokes.length - 1];
    		currentStroke.path.push({ x: event.offsetX, y: event.offsetY });
			if(!saved){
				save();
			}
		}
	}

	function stopDrawing() {
		if (drawing){
			isDrawing = false;
			ctx.closePath();
		}
	}
	
	const save = debounce(2500, saveCanvas);

	function clearCanvas() {
		ctx.clearRect(0, 0, canvas.width, canvas.height);
		strokes = [];
	}

	export function getCanvasData() {
		return JSON.stringify(strokes);
	}

	async function saveCanvas() {
		const id = flashcardId;
		const canvasData = getCanvasData();
		console.log("Saving canvas Data...");
		formData.append('canvasData', canvasData));

		const response = await fetch('/canvas', {
			method: 'POST',
			body: formData,
		});


		if (response.ok) {
			console.log('Canvas saved successfully');
		} else {
			console.error('Failed to save canvas data');
		}

	}

	async function loadCanvas(flashcardId) {
	
	}

	function bold() {
		/* Generated by Perplexity on 11/10/24 */
		const selection = quill.getSelection();
		if (selection) {
			quill.format('bold', !quill.getFormat(selection).bold);
			formatStore.update(state => ({ ...state, isBold: quill.getFormat(selection).bold}))
		}
		/* End generated code */
	}

	function italic() {
		const selection = quill.getSelection();
		if (selection) {
			quill.format('italic', !quill.getFormat(selection).italic);
			formatStore.update(state => ({ ...state, isItalic: quill.getFormat(selection).italic}))
		}
	}

	function underline() {
		const selection = quill.getSelection();
		if (selection) {
			quill.format('underline', !quill.getFormat(selection).underline);
			formatStore.update(state => ({ ...state, isUnderline: quill.getFormat(selection).underline}))
		}
	}

	function strikethrough() {
		const selection = quill.getSelection();
		if (selection) {
			quill.format('strike', !quill.getFormat(selection).strike);
			formatStore.update(state => ({ ...state, isStrikethrough: quill.getFormat(selection).strike}))
		}
	}

	function numberedList() {
		const selection = quill.getSelection();
		if (selection) {
			quill.format('list', $formatStore.isNumberedList ? false : 'ordered');
			formatStore.update(state => ({ ...state, isNumberedList: quill.getFormat(selection).list === 'ordered'}))
		}
	}

	function bulletedList() {
		const selection = quill.getSelection();
		if (selection) {
			quill.format('list', $formatStore.isBulletedList ? false : 'bullet');
			formatStore.update(state => ({ ...state, isItalic: quill.getFormat(selection).list === 'bullet'}))
		}
	}
</script>

<div class="relative">

	<div class="editor"></div>
  
	
	<canvas
	  bind:this={canvas}
	  on:mousedown={startDrawing}
	  on:mousemove={draw}
	  on:mouseup={stopDrawing}
	  class="absolute top-[173px] left-[1px] pointer-events-none"
	  style="z-index: 10; background: transparent;"
	></canvas>
  </div>
<div class="flex flex-row items-center justify-start space-x-1 pt-1.5">
	<FileDropdown />
	<EditDropdown />
	<FormatDropdown
		on:bold={() => bold()}
		on:italic={() => italic()}
		on:underline={() => underline()}
		on:strikethrough={() => strikethrough()}
		on:numberedlist={() => numberedList()}
		on:bulletedlist={() => bulletedList()}
	/>
</div>
<div class="flex min-w-80 flex-row flex-wrap items-center justify-start space-x-1 space-y-1 pt-1.5">
	<TextSizeDropdown
		selection={textSize}
		on:select={() => {
			const selection = quill?.getSelection();
			if (selection) {
				quill.format('size', $textSize);
			}
		}}
	/>
	<button
		class="rounded-lg p-1 {$formatStore.isBold
			? 'bg-stone-200 dark:bg-stone-800'
			: 'bg-stone-50 dark:bg-stone-950'} hover:cursor-pointer hover:bg-stone-200 hover:dark:bg-stone-800"
		on:click={() => bold()}
	>
		<Icon icon={Icons.Bold} width="32" height="32" fill={$formatStore.isBold ? activeColor : null} />
	</button>
	<button
		class="rounded-lg p-1 {$formatStore.isItalic
			? 'bg-stone-200 dark:bg-stone-800'
			: 'bg-stone-50 dark:bg-stone-950'} hover:cursor-pointer hover:bg-stone-200 hover:dark:bg-stone-800"
		on:click={() => italic()}
	>
		<Icon icon={Icons.Italic} width="32" height="32" fill={$formatStore.isItalic ? activeColor : null} />
	</button>
	<button
		class="self-end rounded-lg p-1 {$formatStore.isUnderline
			? 'bg-stone-200 dark:bg-stone-800'
			: 'bg-stone-50 dark:bg-stone-950'} hover:cursor-pointer hover:bg-stone-200 hover:dark:bg-stone-800"
		on:click={() => underline()}
	>
		<Icon icon={Icons.Underline} width="32" height="32" fill={$formatStore.isUnderline ? activeColor : null} />
	</button>
	<button
		class="rounded-lg p-1 {$formatStore.isStrikethrough
			? 'bg-stone-200 dark:bg-stone-800'
			: 'bg-stone-50 dark:bg-stone-950'} hover:cursor-pointer hover:bg-stone-200 hover:dark:bg-stone-800"
		on:click={() => strikethrough()}
	>
		<Icon
			icon={Icons.Strikethrough}
			width="32"
			height="32"
			fill={$formatStore.isStrikethrough ? activeColor : null}
		/>
	</button>
	<button
		class="rounded-lg p-1 {$formatStore.isNumberedList
			? 'bg-stone-200 dark:bg-stone-800'
			: 'bg-stone-50 dark:bg-stone-950'}
			hover:cursor-pointer hover:bg-stone-200 hover:dark:bg-stone-800"
		on:click={() => numberedList()}
	>
		<Icon
			icon={Icons.NumberedList}
			width="32"
			height="32"
			fill={$formatStore.isNumberedList ? activeColor : null}
		/>
	</button>
	<button
		class="rounded-lg p-1 {$formatStore.isBulletedList
			? 'bg-stone-200 dark:bg-stone-800'
			: 'bg-stone-50 dark:bg-stone-950'} hover:cursor-pointer hover:bg-stone-200 hover:dark:bg-stone-800"
		on:click={() => bulletedList()}
	>
		<Icon
			icon={Icons.BulletedList}
			width="32"
			height="32"
			fill={$formatStore.isBulletedList ? activeColor : null}
		/>
	</button>
	<div class="rounded-lg p-1 hover:cursor-pointer hover:bg-stone-200 hover:dark:bg-stone-800">
		<Icon icon={Icons.AddLink} width="32" height="32" />
	</div>
	<div class="h-8 w-[1px] bg-stone-400 dark:bg-stone-800"></div>
	<div class="rounded-lg p-1 hover:cursor-pointer hover:bg-stone-200 hover:dark:bg-stone-800">
		<Icon icon={Icons.AddPhoto} width="32" height="32" />
	</div>
	<button
		class="rounded-lg p-1 {$formatStore.isDrawing
			? 'bg-stone-200 dark:bg-stone-800'
			: 'bg-stone-50 dark:bg-stone-950'} hover:cursor-pointer hover:bg-stone-200 hover:dark:bg-stone-800"
		on:click={() => toggleDrawing()}
	>
		<Icon
			icon={Icons.Draw}
			width="32"
			height="32"
			fill={$formatStore.isDrawing ? activeColor : null}
		/>
	</button>
	<button
		class="rounded-lg p-1
			? 'bg-stone-200 dark:bg-stone-800'
			: 'bg-stone-50 dark:bg-stone-950'} hover:cursor-pointer hover:bg-stone-200 hover:dark:bg-stone-800"
		on:click={() => clearCanvas()}
	>
		<Icon
			icon={Icons.Clear}
			width="32"
			height="32"
		/>
	</button>
</div>

