revoke delete on table "public"."flashcard_canvas" from "anon";

revoke insert on table "public"."flashcard_canvas" from "anon";

revoke references on table "public"."flashcard_canvas" from "anon";

revoke select on table "public"."flashcard_canvas" from "anon";

revoke trigger on table "public"."flashcard_canvas" from "anon";

revoke truncate on table "public"."flashcard_canvas" from "anon";

revoke update on table "public"."flashcard_canvas" from "anon";

revoke delete on table "public"."flashcard_canvas" from "authenticated";

revoke insert on table "public"."flashcard_canvas" from "authenticated";

revoke references on table "public"."flashcard_canvas" from "authenticated";

revoke select on table "public"."flashcard_canvas" from "authenticated";

revoke trigger on table "public"."flashcard_canvas" from "authenticated";

revoke truncate on table "public"."flashcard_canvas" from "authenticated";

revoke update on table "public"."flashcard_canvas" from "authenticated";

revoke delete on table "public"."flashcard_canvas" from "service_role";

revoke insert on table "public"."flashcard_canvas" from "service_role";

revoke references on table "public"."flashcard_canvas" from "service_role";

revoke select on table "public"."flashcard_canvas" from "service_role";

revoke trigger on table "public"."flashcard_canvas" from "service_role";

revoke truncate on table "public"."flashcard_canvas" from "service_role";

revoke update on table "public"."flashcard_canvas" from "service_role";

alter table "public"."flashcard_canvas" drop constraint "flashcard_canvas_pkey";

drop index if exists "public"."flashcard_canvas_pkey";

drop table "public"."flashcard_canvas";

create table "public"."canvas" (
    "id" bigint generated by default as identity not null,
    "canvas_data" text
);

insert into canvas (id, canvas_data) values (0, null)

alter table "public"."canvas" enable row level security;

CREATE UNIQUE INDEX canvas_pkey ON public.canvas USING btree (id);

alter table "public"."canvas" add constraint "canvas_pkey" PRIMARY KEY using index "canvas_pkey";

grant delete on table "public"."canvas" to "anon";

grant insert on table "public"."canvas" to "anon";

grant references on table "public"."canvas" to "anon";

grant select on table "public"."canvas" to "anon";

grant trigger on table "public"."canvas" to "anon";

grant truncate on table "public"."canvas" to "anon";

grant update on table "public"."canvas" to "anon";

grant delete on table "public"."canvas" to "authenticated";

grant insert on table "public"."canvas" to "authenticated";

grant references on table "public"."canvas" to "authenticated";

grant select on table "public"."canvas" to "authenticated";

grant trigger on table "public"."canvas" to "authenticated";

grant truncate on table "public"."canvas" to "authenticated";

grant update on table "public"."canvas" to "authenticated";

grant delete on table "public"."canvas" to "service_role";

grant insert on table "public"."canvas" to "service_role";

grant references on table "public"."canvas" to "service_role";

grant select on table "public"."canvas" to "service_role";

grant trigger on table "public"."canvas" to "service_role";

grant truncate on table "public"."canvas" to "service_role";

grant update on table "public"."canvas" to "service_role";


